apiVersion: apps/v1
kind: Deployment
metadata: 
   name: mysql
spec: 
   replicas: 1
   selector:
      matchLabels:
         app: mysql
   strategy:
      type: Recreate
   template:
      metadata:
         labels:
            app: mysql
      sepc:
         containers:
            - image: mysql:latest
            name: mysql
            env:
               - name: MYSQL_ROOT_PASSWORD
               valueFrom:
                  secretKeyRef:
                     name: mysql-secret
                     key: password
            ports:
               -containerPort: 3306
               name: mysql